### ISSUE TITLE
2.0 Tracking

### ISSUE THREAD

**Issue by Kircheneer** [networktocode/diffsync#232]
I think we should get the following things over the line in preparation for 2.0:

- [x] #231 (if we want to do it)
- [x] #219
- [ ] Thinking about further necessary breaking changes
- [ ] #228 (including any changes made in other items)
- [x] #84
- [x] #233 
- [x] Pydantic 2.0

**Comment by jamesharr** [comment]
Thoughts on bumping to Pydantic v2?

It's not 100% backwards compatible, but they did improve performance a decent amount. Some libraries like Beanie will support both v1 and v2 and it might actually be the case that diffsync can support both.

If no one else is doing it, I might spend a little bit of time POC'ing a bump

**Comment by Kircheneer** [comment]
FYI: We will merge #114 before cutting the release but the other changes will be postponed in favor of getting Pydantic 2.0 support out there sooner rather than later.
